source 'https://github.com/CocoaPods/Specs.git'
 
xcodeproj 'Incognito.xcodeproj'
platform :ios, ‘9.0’
use_frameworks!                   # [1] use dynamic frameworks
 
pod 'AeroGearOAuth2', '0.5.1'     # [2] use AeroGearOAuth2 0.3.0 version